name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

#      - name: Set up JDK 11
#        uses: actions/setup-java@v3
#        with:
#          java-version: '11'
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'


      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          wrapper-cache-enabled: true

      - name: Build and run tests
        run: ./gradlew build test

      - name: Generate test reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: build/reports/tests/test

      # Optional: Docker steps for building and running the app
      - name: Build Docker image
        run: docker build -t martial-arts-api:latest -f docker/Dockerfile .

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Run Docker Compose
        run: docker-compose up -d

      - name: Clean up Docker Compose
        if: always()
        run: docker-compose down

